apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
spec:
  type: ClusterIP
  selector:
    app: jenkins-server
  ports:
  - name: web
    port: 8080
    targetPort: httpport

  - name: agent
    port: 50000
    targetPort: jnlpport