apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
  name: spark-driver
  namespace: spark
spec:
  clusterIP: None
  ports:
  - name: http
    port: 30020
    targetPort: 30020
  selector:
    app: spark-history-server
